apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "custom-mysql.fullname" . }}
  labels:
    {{- include "custom-mysql.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  hostPath:
    path: {{ .Values.pvc.mountPath }}
