apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "custom-mysql.fullname" . }}
  labels:
    {{- include "custom-mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
