- name: Add an apt signing key
  apt_key:
    url: "{{ apt_key }}"
    state: present

- name: Add apt repository
  apt_repository:
    repo: "{{ apt_repo }}"
    state: present

- name: Install dependencies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes

- name: Add {{ user }} user to docker group
  user:
    name: "{{ user }}"
    group: docker
