- name: Installing Dependency for Ubuntu, Docker, Kubernetes
  hosts: all
  become: true
  roles:
    - role: ubuntu-dependency
    - role: docker
    - role: kubernetes

- name: Creating K8s Cluster
  hosts: all
  become: true
  tasks:

## Initialize the Kubernetes cluster with kubeadm.
  - name: Initialize the Kubernetes cluster using kubeadm
    become: yes
    command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16

## Setup the kube config file for the vagrant user to access the Kubernetes cluster.
  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install calico pod network
    become: false
    shell: kubectl apply -f calico.yaml

## Generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command.
  - name: Generate join command
    become: false
    command: kubeadm token create --print-join-command
    register: join_command
 
  - name: Copy
    become: false
    local_action: 
      module: copy 
      content: "{{ join_command.stdout_lines[0] }}"
      dest: "{{ playbook_dir }}/join-command"

## Get kubeconfig file from master
  - name: Get kubeconfig
    fetch:
      src: .kube/config
      dest: "{{ playbook_dir }}/kube_config"
      flat: yes